spring:
  application:
    name: service-registry

server:
  port: 5000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:5000/eureka
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0